apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity.fullname" . }}
  labels:
    {{- include "identity.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "identity.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "identity.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: identity
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: IDENTITY_HTTP_ADDR
              value: {{ .Values.config.httpAddr | quote }}
            - name: IDENTITY_DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbUrlSecretName }}
                  key: url
            - name: IDENTITY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.jwtSecretName }}
                  key: secret
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
